questions = [
{
"name":"is the country landlocked (it has no coastline)",
"is the country landlocked (it has no coastline)": True,
},
{
"name":"is the country in africa",
 "is the country in africa":True,
},
{ 
"name":"is the country in oceania",
"is the country in oceania":True, 
},
{ 
"name":"is the country in europe",
 "is the country in europe":True,
},
{ 
"name":"is the country in north america",
"is the country in north america":True, 
},
{
"name":"is the country in south america",
 "is the country in south america":True,
},
{ 
"name":"is the country in asia",
"is the country in asia":True, 
},
{
"name":"is the country in the northern hemesphere",
 "is the country in the northern hemesphere":True, 
},
{
"name":"is the country in the southern hemesphere",
 "is the country in the southern hemesphere":True,
},]
        
countries = [
{
"name" : 'afghanistan',            
"landlocked": True,
"inafrica": False,
"inoceania": False,
"ineurope": False,
"innorthamerica": False,
"insouthamerica": False,
"inasia": True,
"northernhemesphere": True,
"southernhemesphere": False,
"size": '652860',
"population": '40',
},
{
    "name" : 'albania',
            
            
    
    "landlocked": False,
    "inafrica": False,
    "inoceania": False,
    "ineurope": True,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": False,
    "size": '28748',
    "population": '3.812',
},
{
    "name" : 'algeria',
    
    
    
    "landlocked": False,
    "inafrica": True,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": False,
    "size": '2382000',
    "population": '44.62',
},
{
    "name" : 'andorra',
    
    
    
    "landlocked": True,
    "inafrica": False,
    "inoceania": False,
    "ineurope": True,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": False,
    "size": '468',
    "population": '0.077354',
},
{
    "name" : 'angola',
    
    
    
    "landlocked": False,
    "inafrica": True,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": False,
    "southernhemesphere": True,
    "size": '1247000',
    "population": '34',
},
{
    "name" : 'antigua and barbuda',
    
    
    
    "landlocked": False,
    "inafrica": False,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": True,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": False,
    "size": '440',
    "population": '0,098728',
},
{
    "name" : 'argentina',
    
    
    
    "landlocked": False,
    "inafrica": False,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": True,
    "inasia": False,
    "northernhemesphere": False,
    "southernhemesphere": True,
    "size": '2780400',
    "population": '45',
},
{
    "name" : 'armenia',
    
    
    
    "landlocked": True,
    "inafrica": False,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": True,
    "northernhemesphere": True,
    "southernhemesphere": False,
    "size": '',
    "population": '2.968',
},
{
    "name" : 'australia',
    
    
    
    "landlocked": False,
    "inafrica": False,
    "inoceania": True,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": False,
    "southernhemesphere": True,
    "size": '7688000',
    "population": '25.74',
},
{
    "name" : 'austria',
    
    
    
    "landlocked": True,
    "inafrica": False,
    "inoceania": False,
    "ineurope": True,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": False,
    "size": '83871',
    "population": '8.95',
},
{
    "name" : 'azerbaijan',
    
    
    
    "landlocked": False,
    "inafrica": False,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": True,
    "northernhemesphere": True,
    "southernhemesphere": False,
    "size": '86600',
    "population": '10.15',

    
},

{
    "name" : 'Bahrain',	

    "landlocked": False,
    "inafrica": False,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": True,
    "northernhemesphere": True,
    "southernhemesphere": False,
    "size": '786',
    "population": '10.15',
    
},
    {
    "name" : 'Bangladesh',
    
    "landlocked": False,
    "inafrica": False,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": True,
    "northernhemesphere": True,
    "southernhemesphere": False,
    "size": '148460',
    "population": '10.15',
},
    {
    "name" : 'Barbados',
        
    "landlocked": False,
    "inafrica": False,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": True,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": False,
    "size": '431',
    "population": '10.15',    
},

    {
    "name" : 'Belarus',
        
    "landlocked": True,
    "inafrica": False,
    "inoceania": False,
    "ineurope": True,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": False,
    "size": '207600',
    "population": '10.15',    
},

    {
    "name" : 'Belgium',
        
    "landlocked": False,
    "inafrica": False,
    "inoceania": False,
    "ineurope": True,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": False,
    "size": '30528',
    "population": '10.15',    
},

    {
    "name" : 'Belize',
        
    "landlocked": False,
    "inafrica": False,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": True,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": False,
    "size": '22966',
    "population": '10.15',    
},
	
    {
    "name" : 'Benin',
        
    "landlocked": False,
    "inafrica": True,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": False,
    "size": '114763',
    "population": '10.15',    
},

    {
    "name" : 'Bermuda',
        
    "landlocked": False,
    "inafrica": False,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": True,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": False,
    "size": '54',
    "population": '10.15',    
},

    {
    "name" : 'Bhutan',
        
    "landlocked": True,
    "inafrica": False,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": True,
    "northernhemesphere": True,
    "southernhemesphere": False,
    "size": '38394',
    "population": '10.15',    
},
	
    {
    "name" : 'Bolivia',
        
    "landlocked": True,
    "inafrica": False,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": True,
    "inasia": False,
    "northernhemesphere": False,
    "southernhemesphere": True,
    "size": '1098581',
    "population": '10.15',    
},

    {
    "name" : 'Bosnia and Herzegovina',
        
    "landlocked": False,
    "inafrica": False,
    "inoceania": False,
    "ineurope": True,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": False,
    "size": '51209',
    "population": '10.15',    
},

    {
    "name" : 'Botswana',
        
    "landlocked": True,
    "inafrica": True,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": False,
    "southernhemesphere": True,
    "size": '581730',
    "population": '10.15',    
},

    {
    "name" : 'Brazil',
        
    "landlocked": False,
    "inafrica": False,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": True,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": True,
    "size": '8515767',
    "population": '10.15',    
},
	
    {
    "name" : 'Brunei',
        
    "landlocked": False,
    "inafrica": False,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": True,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": True,
    "size": '5765',
    "population": '10.15',    
},

    {
    "name" : 'Bulgaria',
        
    "landlocked": False,
    "inafrica": False,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": True,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": True,
    "size": '111002',
    "population": '10.15',    
},

    {
    "name" : 'Burkina Faso',
        
    "landlocked": False,
    "inafrica": False,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": True,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": True,
    "size": '274222',
    "population": '10.15',    
},

    {
    "name" : 'Burundi',
        
    "landlocked": False,
    "inafrica": False,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": True,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": True,
    "size": '27834',
    "population": '10.15',    
},

{"name" : 'Cambodia'	,"size": '	181035	'	, "population": '	16944826	'	,   
     "landlocked": False,
    "inafrica": False,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": True,
    "northernhemesphere": True,
    "southernhemesphere": False, },

{"name" : 'Cameroon'	,"size": '	475442	'	, "population": '	28647293	'	, 
     "landlocked": False,
    "inafrica": True,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": False,   },
{"name" : 'Canada'	,"size": '	9984670	'	, "population": '	38781292	'	,   
     "landlocked": False,
    "inafrica": False,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": True,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": False, },
{"name" : 'Cape Verde'	,"size": '	4033	'	, "population": '	598682	'	,  
      "landlocked": False,
    "inafrica": True,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": False, },  
{"name" : 'Central African Republic'	,"size": '	622984	'	, "population": '	5742316	'	, 
      "landlocked": True,
    "inafrica": True,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": False, },   
{"name" : 'Chad'	,"size": '	1284000	'	, "population": '	18278568	'	, 
      "landlocked": True,
    "inafrica": True,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": False, },   
{"name" : 'Chile'	,"size": '	756102	'	, "population": '	19629590	'	,   
      "landlocked": False,
    "inafrica": False,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": True,
    "inasia": False,
    "northernhemesphere": False,
    "southernhemesphere": True, }, 
{"name" : 'China'	,"size": '	9596961	'	, "population": '	1425671352	'	,  
      "landlocked": False,
    "inafrica": False,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": True,
    "northernhemesphere": True,
    "southernhemesphere": False, }, 
{"name" : 'Colombia'	,"size": '	1141748	'	, "population": '	52085168	'	,   
      "landlocked": False,
    "inafrica": False,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": True,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": True, },
{"name" : 'Comoros'	,"size": '	1862	'	, "population": '	852075	'	,   
      "landlocked": False,
    "inafrica": True,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": False,
    "southernhemesphere": True, }, 
{"name" : 'Congo'	,"size": '	342000	'	, "population": '	6106869	'	,  
      "landlocked": False,
    "inafrica": True,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": True, },  
{"name" : 'DR Congo'	,"size": '	2344858	'	, "population": '	102262809	'	, 
      "landlocked": False,
    "inafrica": True,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": True, },  
{"name" : 'Costa Rica'	,"size": '	51100	'	, "population": '	5212173	'	, 
      "landlocked": False,
    "inafrica": False,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": True,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": False, }, 
{"name" : 'Croatia'	,"size": '	56594	'	, "population": '	4008617	'	,   
       "landlocked": False,
    "inafrica": False,
    "inoceania": False,
    "ineurope": True,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": False, },
{"name" : 'Cuba'	,"size": '	109884	'	, "population": '	11194449	'	,  
       "landlocked": False,
    "inafrica": False,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": True,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": False,  },
{"name" : 'Cyprus'	,"size": '	9251	'	, "population": '	1260138	'	,  
       "landlocked": False,
    "inafrica": False,
    "inoceania": False,
    "ineurope": True,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": False,  },
{"name" : 'Czech Republic'	,"size": '	78871	'	, "population": '	10495295	'	,  
       "landlocked": True,
    "inafrica": False,
    "inoceania": False,
    "ineurope": True,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": False,  },
{"name" : 'Denmark'	,"size": '	43094	'	, "population": '	5910913	'	,   
       "landlocked": False,
    "inafrica": False,
    "inoceania": False,
    "ineurope": True,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": False, },
{"name" : 'Djibouti'	,"size": '	23200	'	, "population": '	1136455	'	,   
       "landlocked": False,
    "inafrica": True,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": False,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": False, },
{"name" : 'Dominica'	,"size": '	751	'	, "population": '	73040	'	,  
       "landlocked": False,
    "inafrica": False,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": True,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": False,  },
{"name" : 'Dominican Republic	'	,"size": '	48671	'	, "population": '	11332973	'	,  
       "landlocked": False,
    "inafrica": False,
    "inoceania": False,
    "ineurope": False,
    "innorthamerica": True,
    "insouthamerica": False,
    "inasia": False,
    "northernhemesphere": True,
    "southernhemesphere": False,  },

]
